### ISSUE TITLE
Update Getting Started Guide and User Guide for 0.12

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/docs#18]
These should match the guides created by Duende as much as possible.

**Comment by disquisitioner** [comment]
Got it!   Will extract content from the new Getting Started Guide and update what's here.

**Comment by hcientist** [comment]
@mrstegeman is there a link to 

> the guides created by Duende 

I am just finding mozilla-iot (AWESOME) and wondering if (e.g.) Pi3 is currently preferred over a Raspberry Pi 4.

**Comment by mrstegeman** [comment]
@hcientist https://www.okdo.com/project/get-started-with-webthings-gateway-kit/

As for the RPi, no, there is not preference there. The gateway will definitely run better on the Pi 4, but the Pi 3 is more than enough. The only drawback we've found with the Pi 4 is that the Aeotec Z-Stick doesn't work when directly plugged into a Pi 4.
